source 'https://rubygems.org'

gem 'builder'
gem 'jasmine'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-sprockets'
gem 'middleman-syntax'
gem 'middleman-autoprefixer'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'redcarpet'
gem 'json', github: 'flori/json', branch: 'v1.8'
gem 'breakpoint'
